type Country = {
  name: string;
  capital: string;
  continent: string;
};

const Continents: {
  [key: string]: Country[];
} = {
  Africa: [
    { name: "Somaliland", capital: "Hargeisa", continent: "Africa" },
    { name: "Western Sahara", capital: "El-AaiÃºn", continent: "Africa" },
    { name: "Algeria", capital: "Algiers", continent: "Africa" },
    { name: "Angola", capital: "Luanda", continent: "Africa" },
    { name: "Benin", capital: "Porto-Novo", continent: "Africa" },
    { name: "Botswana", capital: "Gaborone", continent: "Africa" },
    { name: "Burkina Faso", capital: "Ouagadougou", continent: "Africa" },
    { name: "Burundi", capital: "Bujumbura", continent: "Africa" },
    { name: "Cameroon", capital: "Yaounde", continent: "Africa" },
    { name: "Cape Verde", capital: "Praia", continent: "Africa" },
    {
      name: "Central African Republic",
      capital: "Bangui",
      continent: "Africa",
    },
    { name: "Chad", capital: "N'Djamena", continent: "Africa" },
    { name: "Comoros", capital: "Moroni", continent: "Africa" },
    {
      name: "Democratic Republic of the Congo",
      capital: "Kinshasa",
      continent: "Africa",
    },
    { name: "Republic of Congo", capital: "Brazzaville", continent: "Africa" },
    { name: "Cote d'Ivoire", capital: "Yamoussoukro", continent: "Africa" },
    { name: "Djibouti", capital: "Djibouti", continent: "Africa" },
    { name: "Egypt", capital: "Cairo", continent: "Africa" },
    { name: "Equatorial Guinea", capital: "Malabo", continent: "Africa" },
    { name: "Eritrea", capital: "Asmara", continent: "Africa" },
    { name: "Ethiopia", capital: "Addis Ababa", continent: "Africa" },
    { name: "Gabon", capital: "Libreville", continent: "Africa" },
    { name: "The Gambia", capital: "Banjul", continent: "Africa" },
    { name: "Ghana", capital: "Accra", continent: "Africa" },
    { name: "Guinea", capital: "Conakry", continent: "Africa" },
    { name: "Guinea-Bissau", capital: "Bissau", continent: "Africa" },
    { name: "Kenya", capital: "Nairobi", continent: "Africa" },
    { name: "Lesotho", capital: "Maseru", continent: "Africa" },
    { name: "Liberia", capital: "Monrovia", continent: "Africa" },
    { name: "Libya", capital: "Tripoli", continent: "Africa" },
    { name: "Madagascar", capital: "Antananarivo", continent: "Africa" },
    { name: "Malawi", capital: "Lilongwe", continent: "Africa" },
    { name: "Mali", capital: "Bamako", continent: "Africa" },
    { name: "Mauritania", capital: "Nouakchott", continent: "Africa" },
    { name: "Mauritius", capital: "Port Louis", continent: "Africa" },
    { name: "Morocco", capital: "Rabat", continent: "Africa" },
    { name: "Mozambique", capital: "Maputo", continent: "Africa" },
    { name: "Namibia", capital: "Windhoek", continent: "Africa" },
    { name: "Niger", capital: "Niamey", continent: "Africa" },
    { name: "Nigeria", capital: "Abuja", continent: "Africa" },
    { name: "Rwanda", capital: "Kigali", continent: "Africa" },
    { name: "Saint Helena", capital: "Jamestown", continent: "Africa" },
    { name: "Sao Tome and Principe", capital: "Sao Tome", continent: "Africa" },
    { name: "Senegal", capital: "Dakar", continent: "Africa" },
    { name: "Seychelles", capital: "Victoria", continent: "Africa" },
    { name: "Sierra Leone", capital: "Freetown", continent: "Africa" },
    { name: "Somalia", capital: "Mogadishu", continent: "Africa" },
    { name: "South Africa", capital: "Pretoria", continent: "Africa" },
    { name: "South Sudan", capital: "Juba", continent: "Africa" },
    { name: "Sudan", capital: "Khartoum", continent: "Africa" },
    { name: "Swaziland", capital: "Mbabane", continent: "Africa" },
    { name: "Tanzania", capital: "Dar es Salaam", continent: "Africa" },
    { name: "Togo", capital: "Lome", continent: "Africa" },
    { name: "Tunisia", capital: "Tunis", continent: "Africa" },
    { name: "Uganda", capital: "Kampala", continent: "Africa" },
    { name: "Zambia", capital: "Lusaka", continent: "Africa" },
    { name: "Zimbabwe", capital: "Harare", continent: "Africa" },
    {
      name: "British Indian Ocean Territory",
      capital: "Diego Garcia",
      continent: "Africa",
    },
  ],
  Antarctica: [
    {
      name: "South Georgia and South Sandwich Islands",
      capital: "King Edward Point",
      continent: "Antarctica",
    },
    {
      name: "French Southern and Antarctic Lands",
      capital: "Port-aux-FranÃ§ais",
      continent: "Antarctica",
    },
    { name: "Antarctica", capital: "N/A", continent: "Antarctica" },
    {
      name: "Heard Island and McDonald Islands",
      capital: "N/A",
      continent: "Antarctica",
    },
  ],
  Asia: [
    { name: "Palestine", capital: "Jerusalem", continent: "Asia" },
    { name: "Afghanistan", capital: "Kabul", continent: "Asia" },
    { name: "Bahrain", capital: "Manama", continent: "Asia" },
    { name: "Bangladesh", capital: "Dhaka", continent: "Asia" },
    { name: "Bhutan", capital: "Thimphu", continent: "Asia" },
    {
      name: "Brunei Darussalam",
      capital: "Bandar Seri Begawan",
      continent: "Asia",
    },
    { name: "Myanmar", capital: "Rangoon", continent: "Asia" },
    { name: "Cambodia", capital: "Phnom Penh", continent: "Asia" },
    { name: "China", capital: "Beijing", continent: "Asia" },
    { name: "India", capital: "New Delhi", continent: "Asia" },
    { name: "Indonesia", capital: "Jakarta", continent: "Asia" },
    { name: "Iran", capital: "Tehran", continent: "Asia" },
    { name: "Iraq", capital: "Baghdad", continent: "Asia" },
    { name: "Israel", capital: "Jerusalem", continent: "Asia" },
    { name: "Japan", capital: "Tokyo", continent: "Asia" },
    { name: "Jordan", capital: "Amman", continent: "Asia" },
    { name: "Kazakhstan", capital: "Astana", continent: "Asia" },
    { name: "North Korea", capital: "Pyongyang", continent: "Asia" },
    { name: "South Korea", capital: "Seoul", continent: "Asia" },
    { name: "Kuwait", capital: "Kuwait City", continent: "Asia" },
    { name: "Kyrgyzstan", capital: "Bishkek", continent: "Asia" },
    { name: "Laos", capital: "Vientiane", continent: "Asia" },
    { name: "Lebanon", capital: "Beirut", continent: "Asia" },
    { name: "Malaysia", capital: "Kuala Lumpur", continent: "Asia" },
    { name: "Maldives", capital: "Male", continent: "Asia" },
    { name: "Mongolia", capital: "Ulaanbaatar", continent: "Asia" },
    { name: "Nepal", capital: "Kathmandu", continent: "Asia" },
    { name: "Oman", capital: "Muscat", continent: "Asia" },
    { name: "Pakistan", capital: "Islamabad", continent: "Asia" },
    { name: "Philippines", capital: "Manila", continent: "Asia" },
    { name: "Qatar", capital: "Doha", continent: "Asia" },
    { name: "Saudi Arabia", capital: "Riyadh", continent: "Asia" },
    { name: "Singapore", capital: "Singapore", continent: "Asia" },
    { name: "Sri Lanka", capital: "Colombo", continent: "Asia" },
    { name: "Syria", capital: "Damascus", continent: "Asia" },
    { name: "Taiwan", capital: "Taipei", continent: "Asia" },
    { name: "Tajikistan", capital: "Dushanbe", continent: "Asia" },
    { name: "Thailand", capital: "Bangkok", continent: "Asia" },
    { name: "Timor-Leste", capital: "Dili", continent: "Asia" },
    { name: "Turkmenistan", capital: "Ashgabat", continent: "Asia" },
    { name: "United Arab Emirates", capital: "Abu Dhabi", continent: "Asia" },
    { name: "Uzbekistan", capital: "Tashkent", continent: "Asia" },
    { name: "Vietnam", capital: "Hanoi", continent: "Asia" },
    { name: "Yemen", capital: "Sanaa", continent: "Asia" },
    { name: "Hong Kong", capital: "N/A", continent: "Asia" },
    { name: "Macau", capital: "N/A", continent: "Asia" },
  ],
  Europe: [
    { name: "Aland Islands", capital: "Mariehamn", continent: "Europe" },
    { name: "Albania", capital: "Tirana", continent: "Europe" },
    { name: "Andorra", capital: "Andorra la Vella", continent: "Europe" },
    { name: "Armenia", capital: "Yerevan", continent: "Europe" },
    { name: "Austria", capital: "Vienna", continent: "Europe" },
    { name: "Azerbaijan", capital: "Baku", continent: "Europe" },
    { name: "Belarus", capital: "Minsk", continent: "Europe" },
    { name: "Belgium", capital: "Brussels", continent: "Europe" },
    {
      name: "Bosnia and Herzegovina",
      capital: "Sarajevo",
      continent: "Europe",
    },
    { name: "Bulgaria", capital: "Sofia", continent: "Europe" },
    { name: "Croatia", capital: "Zagreb", continent: "Europe" },
    { name: "Cyprus", capital: "Nicosia", continent: "Europe" },
    { name: "Czech Republic", capital: "Prague", continent: "Europe" },
    { name: "Denmark", capital: "Copenhagen", continent: "Europe" },
    { name: "Estonia", capital: "Tallinn", continent: "Europe" },
    { name: "Faroe Islands", capital: "Torshavn", continent: "Europe" },
    { name: "Finland", capital: "Helsinki", continent: "Europe" },
    { name: "France", capital: "Paris", continent: "Europe" },
    { name: "Georgia", capital: "Tbilisi", continent: "Europe" },
    { name: "Germany", capital: "Berlin", continent: "Europe" },
    { name: "Gibraltar", capital: "Gibraltar", continent: "Europe" },
    { name: "Greece", capital: "Athens", continent: "Europe" },
    { name: "Guernsey", capital: "Saint Peter Port", continent: "Europe" },
    { name: "Vatican City", capital: "Vatican City", continent: "Europe" },
    { name: "Hungary", capital: "Budapest", continent: "Europe" },
    { name: "Iceland", capital: "Reykjavik", continent: "Europe" },
    { name: "Ireland", capital: "Dublin", continent: "Europe" },
    { name: "Isle of Man", capital: "Douglas", continent: "Europe" },
    { name: "Italy", capital: "Rome", continent: "Europe" },
    { name: "Jersey", capital: "Saint Helier", continent: "Europe" },
    { name: "Kosovo", capital: "Pristina", continent: "Europe" },
    { name: "Latvia", capital: "Riga", continent: "Europe" },
    { name: "Liechtenstein", capital: "Vaduz", continent: "Europe" },
    { name: "Lithuania", capital: "Vilnius", continent: "Europe" },
    { name: "Luxembourg", capital: "Luxembourg", continent: "Europe" },
    { name: "Macedonia", capital: "Skopje", continent: "Europe" },
    { name: "Malta", capital: "Valletta", continent: "Europe" },
    { name: "Moldova", capital: "Chisinau", continent: "Europe" },
    { name: "Monaco", capital: "Monaco", continent: "Europe" },
    { name: "Montenegro", capital: "Podgorica", continent: "Europe" },
    { name: "Netherlands", capital: "Amsterdam", continent: "Europe" },
    { name: "Norway", capital: "Oslo", continent: "Europe" },
    { name: "Poland", capital: "Warsaw", continent: "Europe" },
    { name: "Portugal", capital: "Lisbon", continent: "Europe" },
    { name: "Romania", capital: "Bucharest", continent: "Europe" },
    { name: "Russia", capital: "Moscow", continent: "Europe" },
    { name: "San Marino", capital: "San Marino", continent: "Europe" },
    { name: "Serbia", capital: "Belgrade", continent: "Europe" },
    { name: "Slovakia", capital: "Bratislava", continent: "Europe" },
    { name: "Slovenia", capital: "Ljubljana", continent: "Europe" },
    { name: "Spain", capital: "Madrid", continent: "Europe" },
    { name: "Svalbard", capital: "Longyearbyen", continent: "Europe" },
    { name: "Sweden", capital: "Stockholm", continent: "Europe" },
    { name: "Switzerland", capital: "Bern", continent: "Europe" },
    { name: "Turkey", capital: "Ankara", continent: "Europe" },
    { name: "Ukraine", capital: "Kyiv", continent: "Europe" },
    { name: "United Kingdom", capital: "London", continent: "Europe" },
    { name: "Northern Cyprus", capital: "North Nicosia", continent: "Europe" },
  ],
  Australia: [
    { name: "Nauru", capital: "Yaren", continent: "Australia" },
    { name: "Tokelau", capital: "Atafu", continent: "Australia" },
    { name: "American Samoa", capital: "Pago Pago", continent: "Australia" },
    { name: "Australia", capital: "Canberra", continent: "Australia" },
    {
      name: "Christmas Island",
      capital: "The Settlement",
      continent: "Australia",
    },
    { name: "Cocos Islands", capital: "West Island", continent: "Australia" },
    { name: "Cook Islands", capital: "Avarua", continent: "Australia" },
    { name: "Fiji", capital: "Suva", continent: "Australia" },
    { name: "French Polynesia", capital: "Papeete", continent: "Australia" },
    { name: "Guam", capital: "Hagatna", continent: "Australia" },
    { name: "Kiribati", capital: "Tarawa", continent: "Australia" },
    { name: "Marshall Islands", capital: "Majuro", continent: "Australia" },
    {
      name: "Federated States of Micronesia",
      capital: "Palikir",
      continent: "Australia",
    },
    { name: "New Caledonia", capital: "Noumea", continent: "Australia" },
    { name: "New Zealand", capital: "Wellington", continent: "Australia" },
    { name: "Niue", capital: "Alofi", continent: "Australia" },
    { name: "Norfolk Island", capital: "Kingston", continent: "Australia" },
    {
      name: "Northern Mariana Islands",
      capital: "Saipan",
      continent: "Australia",
    },
    { name: "Palau", capital: "Melekeok", continent: "Australia" },
    {
      name: "Papua New Guinea",
      capital: "Port Moresby",
      continent: "Australia",
    },
    { name: "Pitcairn Islands", capital: "Adamstown", continent: "Australia" },
    { name: "Samoa", capital: "Apia", continent: "Australia" },
    { name: "Solomon Islands", capital: "Honiara", continent: "Australia" },
    { name: "Tonga", capital: "Nuku'alofa", continent: "Australia" },
    { name: "Tuvalu", capital: "Funafuti", continent: "Australia" },
    { name: "Vanuatu", capital: "Port-Vila", continent: "Australia" },
    { name: "Wallis and Futuna", capital: "Mata-Utu", continent: "Australia" },
  ],
  "North America": [
    { name: "Saint Martin", capital: "Marigot", continent: "North America" },
    { name: "Anguilla", capital: "The Valley", continent: "North America" },
    {
      name: "Antigua and Barbuda",
      capital: "Saint John's",
      continent: "North America",
    },
    { name: "Aruba", capital: "Oranjestad", continent: "North America" },
    { name: "Bahamas", capital: "Nassau", continent: "North America" },
    { name: "Barbados", capital: "Bridgetown", continent: "North America" },
    { name: "Bermuda", capital: "Hamilton", continent: "North America" },
    {
      name: "British Virgin Islands",
      capital: "Road Town",
      continent: "North America",
    },
    {
      name: "Cayman Islands",
      capital: "George Town",
      continent: "North America",
    },
    { name: "Cuba", capital: "Havana", continent: "North America" },
    { name: "CuraÃ§ao", capital: "Willemstad", continent: "North America" },
    { name: "Dominica", capital: "Roseau", continent: "North America" },
    {
      name: "Dominican Republic",
      capital: "Santo Domingo",
      continent: "North America",
    },
    { name: "Grenada", capital: "Saint George's", continent: "North America" },
    { name: "Haiti", capital: "Port-au-Prince", continent: "North America" },
    { name: "Jamaica", capital: "Kingston", continent: "North America" },
    { name: "Montserrat", capital: "Plymouth", continent: "North America" },
    { name: "Puerto Rico", capital: "San Juan", continent: "North America" },
    {
      name: "Saint Barthelemy",
      capital: "Gustavia",
      continent: "North America",
    },
    {
      name: "Saint Kitts and Nevis",
      capital: "Basseterre",
      continent: "North America",
    },
    { name: "Saint Lucia", capital: "Castries", continent: "North America" },
    {
      name: "Sint Maarten",
      capital: "Philipsburg",
      continent: "North America",
    },
    {
      name: "Trinidad and Tobago",
      capital: "Port of Spain",
      continent: "North America",
    },
    {
      name: "Turks and Caicos Islands",
      capital: "Grand Turk",
      continent: "North America",
    },
    {
      name: "US Virgin Islands",
      capital: "Charlotte Amalie",
      continent: "North America",
    },
  ],
  "South America": [
    { name: "Argentina", capital: "Buenos Aires", continent: "South America" },
    { name: "Bolivia", capital: "La Paz", continent: "South America" },
    { name: "Brazil", capital: "Brasilia", continent: "South America" },
    { name: "Chile", capital: "Santiago", continent: "South America" },
    { name: "Colombia", capital: "Bogota", continent: "South America" },
    { name: "Ecuador", capital: "Quito", continent: "South America" },
    {
      name: "Falkland Islands",
      capital: "Stanley",
      continent: "South America",
    },
    { name: "Guyana", capital: "Georgetown", continent: "South America" },
    { name: "Paraguay", capital: "Asuncion", continent: "South America" },
    { name: "Peru", capital: "Lima", continent: "South America" },
    { name: "Suriname", capital: "Paramaribo", continent: "South America" },
    { name: "Uruguay", capital: "Montevideo", continent: "South America" },
    { name: "Venezuela", capital: "Caracas", continent: "South America" },
  ],
  "Central America": [
    { name: "Belize", capital: "Belmopan", continent: "Central America" },
    { name: "Canada", capital: "Ottawa", continent: "Central America" },
    { name: "Costa Rica", capital: "San Jose", continent: "Central America" },
    {
      name: "El Salvador",
      capital: "San Salvador",
      continent: "Central America",
    },
    { name: "Greenland", capital: "Nuuk", continent: "Central America" },
    {
      name: "Guatemala",
      capital: "Guatemala City",
      continent: "Central America",
    },
    { name: "Honduras", capital: "Tegucigalpa", continent: "Central America" },
    { name: "Mexico", capital: "Mexico City", continent: "Central America" },
    { name: "Nicaragua", capital: "Managua", continent: "Central America" },
    { name: "Panama", capital: "Panama City", continent: "Central America" },
    {
      name: "Saint Pierre and Miquelon",
      capital: "Saint-Pierre",
      continent: "Central America",
    },
    {
      name: "Saint Vincent and the Grenadines",
      capital: "Kingstown",
      continent: "Central America",
    },
  ],
  US: [{ name: "United States", capital: "Washington", continent: "US" }],
  UM: [
    {
      name: "US Minor Outlying Islands",
      capital: "Washington",
      continent: "UM",
    },
  ],
};

export default Continents;
